=== F-Lauria/Bla_Bla_Bike/xml/Uscita.dtd
<!ELEMENT USCITA (LUOGO, TIPO_DI_USCITA, LIVELLO_DI_DIFFICOLTA, DURATA, LUNGHEZZA, DISLIVELLO, DATA)>
<!ELEMENT LUOGO (#PCDATA)>
<!ELEMENT TIPO_DI_USCITA EMPTY>
<!ELEMENT LIVELLO_DI_DIFFICOLTA EMPTY>
<!ELEMENT DURATA (#PCDATA)>
<!ELEMENT LUNGHEZZA (#PCDATA)>
<!ELEMENT DISLIVELLO (#PCDATA)>
<!ELEMENT DATA (#PCDATA)>

<!ATTLIST USCITA titolo CDATA #REQUIRED>
<!ATTLIST TIPO_DI_USCITA tipo (corsa | mountainbike) #REQUIRED>
<!ATTLIST LIVELLO_DI_DIFFICOLTA livello (basso | medio | alto) #REQUIRED>
<!ATTLIST DATA ora CDATA #IMPLIED>

=== F-Lauria/Bla_Bla_Bike/xml/Esempio.xml
<? XML version='1.0' ?>
<!DOCTYPE USCITA SYSTEM 'Uscita.dtd' >

<USCITA titolo='Bombaaaaaaaaaa'>

    <LUOGO>
        GENOVA
    </LUOGO>

    <TIPO_DI_USCITA tipo='mountain bike'/>

    <LIVELLO_DI_DIFFICOLTA livello='alto'/>

    <DURATA>
        9 ore
    </DURATA>

    <LUNGHEZZA>
        40 km
    </LUNGHEZZA>

    <DISLIVELLO>
        100 m
    </DISLIVELLO>

    <DATA ora='05:00:00'>
        2018-03-30
    </DATA>

</USCITA>
